services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: king_db
      POSTGRES_PASSWORD: pass_db
      POSTGRES_DB: login_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: